### ISSUE TITLE
Missing live_persist_config.json

### ISSUE THREAD

**Issue by kevinports** [Spacebrew/spacebrew#41]
I'm following README as instructed and when running

```
node node_server_forever.js
```

or

```
node node_server.js
```

I get a warning:

```
warn: [loadRoutes] live routes config file does not exist live_persist_config.json
```

and a message is served to the browser "Not implemented".

Not sure what the problem is here.

**Comment by heaversm** [comment]
I still get this issue no matter how many times I start up the server.
