### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by q2dg** [Spacebrew/spacebrew#61]
Last commit is from several months ago and activity has reduced a lot from last year to now.
I ask to know if there are any plans/ideas/roadmap to relaunch this project.
Thanks

**Comment by adenine** [comment]
It is still being worked on and used. Many of the efforts are now on
stabilizing the sandbox server and writing more examples. Please submit
suggestions for features on github. We have talked about quite a few
additions, but have focused more on seeing how it is being used without
complicating it further.

We will take the task of publishing our roadmap. Good suggestion.

Best Regards,
Joshua


On Tue, Sep 29, 2015 at 1:38 PM, Osqui LittleRiver <notifications@github.com

**Comment by q2dg** [comment]
Ok, thanks a lot for your answer. Knowing this, I'll close the issue, then.

I'd suggest, though, adding a download link in "How to get it" section of http://docs.spacebrew.cc/about because the lack of it gives the feeling (in fact, all the text of this paragraph) that this project is a bit secondary.
