### ISSUE TITLE
Error when trying spacebrew: the server responded with a status of 426 (Upgrade Required)?

### ISSUE THREAD

**Issue by arthursw** [Spacebrew/spacebrew#66]
_Note: Stackoverflow question [here](http://stackoverflow.com/q/35515398/719276)._

 1. I cloned the [Spacebrew repo][1]
 2. I installed the `websocket` and the `forever` modules (`npm install ws` and `npm install forever-monitor`)
 3. I started Spacebrew (`node node_server_forever.js`)
 4. I went to `http://localhost:9000/` or `http://localhost:9000/admin/index.html` on my browser and the page displays:

> Upgrade Required

There are two errors on the console:

    http://localhost:9000/favicon.ico
     Failed to load resource: the server responded with a status of 426 
     (Upgrade Required)
    http://localhost:9000/
     Failed to load resource: the server responded with a status of 426
     (Upgrade Required)

Did I miss something?

  [1]: https://github.com/Spacebrew/spacebrew

**Comment by quinkennedy** [comment]
The admin interface is not hosted by the SB Server. It is a static page. There is a copy accessible at http://spacebrew.github.io/spacebrew/admin/admin.html which will attempt to connect to a localhost SB server on port 9000. you can provide querystrings to connect to a remote server or different port: http://spacebrew.github.io/spacebrew/admin/admin.html?server=specialdoma.in&port=9999

**Comment by arthursw** [comment]
Ok, I didn't understand this part + I run into [this issue](https://github.com/Spacebrew/spacebrew/issues/55) because I was using an old version of node.js. Spacebrew is great, thanks!! You could just add a link to [the tutorials](http://docs.spacebrew.cc/tutorials) in the readme to welcome new users even more warmly.
