### ISSUE TITLE
Have server serve something helpful if you send it an HTTP request

### ISSUE THREAD

**Issue by quinkennedy** [Spacebrew/spacebrew#67]
or at least something useful in the console? going to http://localhost:9000 seems to be a common expectation for finding the admin interface.

**Comment by robotconscience** [comment]
@quinkennedy Can you check out the http branch? I think that's all we need to do!

**Comment by quinkennedy** [comment]
added notes to commit 5bed0977bb5790c2a5ce0006d0f0fbade4a1feb3

**Comment by robotconscience** [comment]
@quinkennedy closing!
